name: Run Kaggle Notebook and Expose Ollama API

on:
  workflow_dispatch: # Permite acionamento manual

jobs:
  deploy_and_run_kaggle_notebook:
    runs-on: ubuntu-latest
    outputs:
      ngrok_url: ${{ steps.retrieve_ngrok_url.outputs.NGROK_URL_OUTPUT }}
    env:
      # NGROK_AUTHTOKEN_USER é o token Ngrok fornecido pelo usuário.
      # Este token deve ser configurado como um segredo no ambiente do notebook Kaggle.
      NGROK_AUTHTOKEN_USER: ${{ secrets.NGROK_AUTHTOKEN_USER }}
      # KAGGLE_USER_FOR_SLUG é o nome de usuário Kaggle para formar o slug do kernel.
      # As credenciais completas do Kaggle (username e key) estão hardcoded abaixo.
      KAGGLE_USER_FOR_SLUG: "bgzinn"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Configure Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          # Credenciais Kaggle diretamente no workflow, conforme solicitado.
          # ATENÇÃO: Isto expõe suas credenciais no arquivo de workflow.
          printf "%s" '{"username":"bgzinn","key":"55824846e3fff4618538582c58e4969a"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          echo "Debug: Contents of ~/.kaggle/kaggle.json:"
          cat ~/.kaggle/kaggle.json
          echo # For a new line in the log

      - name: Create kernel metadata file
        id: kernel_meta
        env:
          # KERNEL_SLUG_ENV será definido dentro do script e exportado para GITHUB_ENV
          # KAGGLE_USER_FOR_SLUG é usado para construir o KERNEL_SLUG_ENV
          pass # KAGGLE_USER_FOR_SLUG já está no env do job
        run: |
          KERNEL_SLUG="${{ env.KAGGLE_USER_FOR_SLUG }}/ollama-qwen3-14b-runner"
          echo "KERNEL_SLUG_ENV=$KERNEL_SLUG" >> "$GITHUB_ENV"
          python3 -c "
import json
import os

kernel_slug = os.environ['KERNEL_SLUG_ENV']
metadata = {
    'id': kernel_slug,
    'title': 'Ollama Qwen3 14B Runner',
    'code_file': 'ollama_kaggle_runner.ipynb',
    'language': 'python',
    'kernel_type': 'notebook',
    'is_private': True,
    'enable_gpu': True,
    'enable_internet': True,
    'dataset_sources': [],
    'competition_sources': [],
    'kernel_sources': []
}

with open('kernel-metadata.json', 'w') as f:
    json.dump(metadata, f, indent=2)

print(f'kernel-metadata.json created for kernel {kernel_slug} using Python json.dump')
"
          echo "Debug: Contents of kernel-metadata.json:"
          cat kernel-metadata.json
          echo # For a new line in the log

      - name: Push and run Kaggle Notebook
        run: |
          if [ ! -f ollama_kaggle_runner.ipynb ]; then
            echo "ERROR: ollama_kaggle_runner.ipynb not found in the repository root."
            exit 1
          fi
          kaggle kernels push -p ./

      - name: Wait for notebook to initialize and retrieve Ngrok URL
        id: retrieve_ngrok_url
        run: |
          echo "Waiting for Kaggle notebook to start and generate Ngrok URL (this might take 10-15 minutes)..."
          sleep 900 # 15 minutos de espera

          echo "Attempting to retrieve Ngrok URL from kernel output..."
          mkdir -p ./kaggle_output
          # Tentar baixar o output algumas vezes, pois pode levar um tempo para aparecer
          for i in {1..3}
          do
            echo "Attempt $i to download kernel output..."
            if kaggle kernels output -k "${{ env.KERNEL_SLUG_ENV }}" -p ./kaggle_output --force; then
              if [ -f ./kaggle_output/ngrok_url.txt ]; then
                NGROK_URL=$(cat ./kaggle_output/ngrok_url.txt | tr -d '[:space:]')
                if [ -n "$NGROK_URL" ]; then
                  echo "NGROK_URL_OUTPUT=$NGROK_URL" >> "$GITHUB_OUTPUT"
                  echo "Successfully retrieved Ngrok URL: $NGROK_URL"
                  exit 0 # Sucesso, sair do loop e do script
                else
                  echo "Warning: ngrok_url.txt is empty on attempt $i."
                fi
              else
                echo "Warning: ngrok_url.txt not found in Kaggle kernel output on attempt $i."
                echo "Files in ./kaggle_output on attempt $i:"
                ls -l ./kaggle_output
              fi
            else
              echo "Warning: Failed to download Kaggle kernel output on attempt $i."
            fi
            if [ $i -lt 3 ]; then
              echo "Waiting 60 seconds before next attempt..."
              sleep 60
            fi
          done

          echo "Error: Failed to retrieve Ngrok URL after multiple attempts."
          echo "Attempting to get kernel status and logs for debugging..."
          kaggle kernels status "${{ env.KERNEL_SLUG_ENV }}" || echo "Failed to get kernel status."
          kaggle kernels logs "${{ env.KERNEL_SLUG_ENV }}" || echo "Failed to get kernel logs."
          exit 1
        env:
          KERNEL_SLUG_ENV: ${{ env.KERNEL_SLUG_ENV }}

      - name: Display Ngrok URL (from job output)
        run: |
          echo "The Ngrok URL for the Ollama API should be available as a job output on the GitHub Actions summary page for this run."
          echo "You can access it in subsequent jobs using: 
eeds.deploy_and_run_kaggle_notebook.outputs.ngrok_url"
          echo "For direct access in this step (if needed): ${{ steps.retrieve_ngrok_url.outputs.NGROK_URL_OUTPUT }}"

